### ISSUE TITLE
Table input doesn't page through data when only `height` is set.

### ISSUE THREAD

**Issue by simond** [observablehq/inputs#261] opened 2024-03-07 09:40 UTC
I have a simple Framework page that contains some sample data (over 10,000 records) and a table. When setting the `height` of the table to any value the table does not scroll through the full results of the data, it simply scrolls to the end of the first set of rows

Markdown:
````
# Sample
```js
const d = FileAttachment("./data/sample.csv").csv({typed: true});
```

## Table of data:
```js
Inputs.table(d, {
    height: 400
})
```
````

If I change the table to include the number of rows to display the scrolling works as expected:
````
```js
Inputs.table(d, {
    rows: 18, 
    height: 400
})
```
````

**Comment by mootari** [comment] 2024-03-07 10:21
Duplicate of #248

The workaround is to materialize all rows by e.g. specifying `{rows: Infinity}`.

**Closed by mootari** 2024-03-07 10:21 UTC
Labels: bug
