### ISSUE TITLE
Inputs.file(url:{http(s):/address})

### ISSUE THREAD

**Issue by kimmolinna** [observablehq/inputs#203] opened 2021-12-01 06:59 UTC
Input file from a http(s)-address to memory.

**Comment by mbostock** [comment] 2021-12-04 17:28
I’m guessing this is a duplicate of #192? If not, please let me know more specifically what you are asking for.

If you want a FileAttachment-like object for a given URL, see https://github.com/observablehq/stdlib/issues/245.

**Closed by mbostock** 2021-12-04 17:28 UTC

**Comment by kimmolinna** [comment] 2021-12-04 20:01
Thank you very much. I meant exactly observablehq/stdlib#245. I would like to load parquet-files from web.
